### PR TITLE
Updating README.md 

### PR DESCRIPTION
**Pull request by geramirez**
Thoughts? 
- Change schema version name to string
- Remove project org. -- this should just be a repo for schemas
- Remove system.yaml since it's deprecated
- Updated component.yaml to current v2 fields, but removed documentation_completed
  and implementation_status as to not encourage thier usage. These two fields stayed in the
  validator files because they are techincally part of 2.0.0
- Left certifications and standards example... but maybe they should removed until they
  also have validators

### CODE REVIEW

**Comment by afeld** [comment]
Not going to be able to address this fully right now, but I promise we will come back to it soon!

**Comment by afeld** [comment]
This was superseded by https://github.com/opencontrol/schemas/pull/20, which updated the README for V3. Still game to remove the example file if you want to merge from `master` or do a separate pull! Sorry for being crazy this week.

**Comment by geramirez** [comment]
No problem, I'll update the PR

**Comment by afeld** [comment]
Closing as stale.

**Pull request closed without merging**
